:sparkles: TO LOWERCASE
Androz2091/AndrozDevBot pull request #3
Opened 2021-08-29 15:50 UTC by Yan-Jobs

2s seriously 🤷‍♂️

2021-08-29 17:05 UTC, RealHinome requested changes
/help|please|aide/i.test(message.content) instead for respect the precedent code

2021-08-29 17:16 UTC, Yan-Jobs commented
> /help|please|aide/i.test(message.content) instead for respect the precedent code

Ok I will see that later

2021-08-29 18:37 UTC, KaKi87 commented
You can also add variants like "pls", "plz", "svp".

2021-08-30 09:05 UTC, Yan-Jobs commented
@KaKi87 @RealHinome done

2021-08-30 09:06 UTC, Yan-Jobs commented
Also I have also maybe format the code 🤷‍♂️

2025-02-01 20:57 UTC, Androz2091 approved these changes
LGTM!

2025-02-01 21:38 UTC, closed without merging

2025-02-01 21:38 UTC, Androz2091 commented
committed and added as a co-author